### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by anatagawa** [alekmaul/pvcollib#1]
J'ai suivi le **wiki** , malgré que tout soit fait pour linux.

- Le **Make.exe** n'étant pas présent dans le répertoire **bin**

- Le Makefile étant incompatible pour windows pour certaine commandes .

J'obtient sous Windows cette erreur ci , après avoir mis un Make, et modifié le makefile  pour le helloworld

**`
?ASlink-Error-Bad offset in library file c:/colecodev/lib/collib.lib(video22)
`**

Ce qui est assez embêtant.

**Comment by alekmaul** [comment]
Bonjour,
Le makefile utilise effectivement une couche msys pour fonctionner mais je compile aussi sous windows sans pb avec cette couche msys (je suis sous windows). Je vais rajouter le fait qu'il faut un environnement de ce type dans le wiki.
Pour le bad offset, jamais eu ce problème. Je peux voir ce que tu as modifié dans le makefile ?

**Comment by anatagawa** [comment]
http://pastebin.anatagawa.fr/?298baed02d1fb210#3UL6naLDHL5Ekx8VQTGpMf7G+KWZTk+y9VtuZRZQkm4=

c'est pas grand chose, mais ca me permet de l'utiliser correctement sous windows avec Visual Studio Code.

**Comment by alekmaul** [comment]
ok, merci, je voulais aussi montrer comment compiler avec vscode dans le wiki, je stocke tout cela.
Pour info, le pb concernant la compilation vient du fait que msys compile en mode UNIX et donc, les fins de lignes sont différentes. Je vais aussi modifier en conséquence le wiki pour expliquer comment recompiler la lib. Tout sera disponible ce week end.

**Comment by anatagawa** [comment]
J'ai pris les dernières source , fait une compilation de la lib , et plus un seul warning. Du tout bon.

**Comment by alekmaul** [comment]
On peut clore le pb alors :)
