### ISSUE TITLE
Pal or Ntsc avec vid_freq

### ISSUE THREAD

**Issue by anatagawa** [alekmaul/pvcollib#2]
J'ai testé l'affichage du **vid_freq** pour savoir si on est en Pal ou Ntsc , présent dans les exemples, et celui-ci m'affiche toujours NTSC quelque soit la fréquence de **BlueMSX** ou **EmulTwo**

Cela fonctionne t'il avec les émulateurs , ou uniquement qu'avec une vrai machine ?

J'utilise la dernière version de la lib.

**Comment by alekmaul** [comment]
cela fonctionne uniquement sur une vrai machine ou alors il faut une rom PAL et une ROM NTSC du bios pour voir la différence.
Et c'est bien vid_freq qu'il faut utiliser pour cela. En fait, vid_freq est utile si tu as un menu option pour le changer de PAL vers NTSC. c'est tout. La musique s'adapte ensuite automatiquement si tu en as.
